dnes = new Date();
mesiac = dnes.getMonth() + 1;
den = dnes.getDate();
kalendar = new Array("Novı rok", "Alexandra", "Daniela", "Drahoslav", "Andrea", "Antónia",
	"Bohuslava/Róbert", "Severín", "Alexej", "Dá¹a", "Malvína",
	"Ernest", "Rastislav", "Radovan", "Dobroslav", "Kristína",
	"Nata¹a", "Bohdana", "Drahomíra", "Dalibor", "Vincent", "Zora",
	"Milo¹", "Timotej", "Gejza", "Tamara", "Bohu¹", "Alfonz",
	"Ga¹par", "Ema", "Emil",
	"Tatiana", "Erika/Erik", "Bla¾ej", "Veronika", "Agáta", "Dorota",
	"Vanda", "Zoja", "Zdenko", "Gabriela", "Dezider", "Perla",
	"Arpád", "Valentín", "Pravoslav", "Ida", "Miloslava", "Jaromír",
	"Vlasta", "Lívia", "Eleonóra", "Etela", "Roman/Romana",
	"Matej", "Frederik/Frederika", "Viktor", "Alexander",
	"Zlatica", "",
	"Albín", "Ane¾ka", "Bohumil/Bohumila", "Kazimír", "Fridrich",
	"Radoslav/Radoslava", "Tomá¹/Róbert", "Alan/Alana", "Franti¹ka",
	"Branislav/Bruno", "Angela/Angelika", "Gregor", "Vlastimil",
	"Matilda", "Svetlana", "Boleslav", "¥ubica", "Eduard", "Jozef",
	"Víazoslav", "Blahoslav", "Beòadik", "Adrián", "Gabriel",
	"Marián", "Emanuel", "Alena", "Soòa", "Miroslav", "Vieroslava",
	"Benjamín",
	"Hugo", "Zita", "Richard", "Izidor", "Miroslava", "Irena",
	"Zoltán/Róbert", "Albert", "Milena", "Igor", "Július", "Estera",
	"Ale¹", "Justína", "Fedor", "Dana/Danica", "Rudolf", "Valér",
	"Jela", "Marcel", "Ervín", "Slavomír", "Vojtech", "Juraj",
	"Marek", "Jaroslava", "Jaroslav", "Jarmila", "Lea",
	"Anastázia",
	"Sviatok práce", "®igmund", "Galina", "Florián", "Lesana/Lesia", "Hermína",
	"Monika/Róbert", "Ingrida", "Roland", "Viktória", "Bla¾ena",
	"Pankrác", "Servác", "Bonifác", "®ofia", "Svetozár", "Gizela",
	"Viola", "Gertrúda", "Bernard", "Zina", "Júlia/Juliana",
	"®elmíra", "Ela", "Urban", "Du¹an", "Iveta", "Viliam", "Vilma",
	"Ferdinand", "Petronela/Petrana",
	"®aneta", "Xénia", "Karolína", "Lenka", "Laura", "Norbert",
	"Róbert", "Medard", "Stanislava", "Margaréta", "Dobroslava",
	"Zlatko", "Anton", "Vasil", "Vít", "Blanka", "Adolf", "Vratislav",
	"Alfréd", "Valéria", "Alojz", "Paulína", "Sidónia", "Ján",
	"Tadeá¹", "Adriana", "Ladislav/Ladislava", "Beata",
	"Peter/Pavol/Petra", "Melánia",
	"Diana", "Berta", "Miloslav", "Prokop", "Cyril/Metod", "Patrik/Patrícia",
	"Oliver", "Ivan", "Lujza", "Amália", "Milota", "Nina", "Margita",
	"Kamil", "Henrich", "Drahomír", "Bohuslav", "Kamila", "Du¹ana",
	"I¾ja/Eliá¹", "Daniel", "Magdaléna", "O¾ga", "Vladimír",
	"Jakub", "Anna/Hana", "Bo¾ena", "Kri¹tof", "Marta", "Libu¹a",
	"Ignác",
	"Bo¾idara", "Gustáv", "Jergu¹", "Dominik/Dominika", "Hortenzia",
	"Jozefína", "©tefánia", "Oskar", "¥ubomíra", "Vavrinec",
	"Zuzana", "Darina", "¥ubomír", "Mojmír", "Marcela", "Leonard",
	"Milica", "Elena/Helena", "Lıdia", "Anabela", "Jana", "Tichomír",
	"Filip", "Bartolomej", "¥udovít", "Samuel", "Silvia", "Augustín",
	"Nikola/Nikolaj", "Ru¾ena", "Nora",
	"Drahoslava", "Linda", "Belo", "Rozália", "Regína", "Alica",
	"Marianna", "Miriama", "Martina", "Oleg", "Bystrík",
	"Mária", "Ctibor", "¥udomil", "Jolana", "¥udmila", "Olympia",
	"Eugénia", "Kon¹tantín", "¥uboslav/¥uboslava", "Matú¹", "Móric",
	"Zdenka", "¥ubo¹/¥ubor", "Vladislav", "Edita", "Cyprián",
	"Václav", "Michal/Michaela", "Jarolím",
	"Arnold", "Levoslav", "Stela", "Franti¹ek", "Viera", "Natália",
	"Eli¹ka", "Brigita", "Dionız", "Slavomíra", "Valentína",
	"Maximilián", "Koloman", "Boris", "Terézia", "Vladimíra",
	"Hedviga", "Luká¹", "Kristián", "Vendelín", "Ur¹u¾a", "Sergej",
	"Alojzia", "Kvetoslava", "Aurel", "Demeter", "Sabína", "Dobromila",
	"Klára", "©imon/Simona", "Aurélia",
	"Denis/Denisa", "", "Hubert", "Karol", "Imrich", "Renáta",
	"René", "Bohumír", "Teodor", "Tibor", "Martin/Maro¹", "Svätopluk",
	"Stanislav", "Irma", "Leopold", "Agnesa", "Klaudia", "Eugen",
	"Al¾beta", "Félix", "Elvíra", "Cecília", "Klement", "Emília",
	"Katarína", "Kornel", "Milan", "Henrieta", "Vratko",
	"Ondrej/Andrej",
	"Edmund", "Bibiána", "Oldrich", "Barbora", "Oto", "Mikulá¹",
	"Ambróz", "Marína", "Izabela", "Radúz", "Hilda", "Otília",
	"Lucia", "Branislava/Bronislava", "Ivica", "Albína", "Kornélia",
	"Sláva/Slávka", "Judita", "Dagmara", "Bohdan", "Adela", "Nade¾da",
	"Adam/Eva", "Vianoce", "©tefan", "Filoména", "Ivana/Ivona", "Milada",
	"Dávid", "Silvester");
dniVMesiaci = new Array(31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);
kalendarIndex = 0;
for (i = 0; i < (mesiac - 1); i++) kalendarIndex += dniVMesiaci[i];
kalendarIndex += (den - 1);
const nameday = document.querySelector("#names");
const namedayspan = nameday.querySelector("span");
namedayspan.textContent = "Dnes má meniny " + kalendar[kalendarIndex] + " | Zajtra má meniny " + kalendar[kalendarIndex + 1]